### ISSUE TITLE
How buffer length can be set ?

### ISSUE THREAD

**Issue by claudioscordino** [baylibre-acme/pyacmegraph#6]
From the documentation, it is unclear how long is the buffer length and how it can be changed.
I need to compute the mean consumption (mW) for a test during about 10 secs.
How can I compute such mean?
Many thanks.

**Comment by sebjan** [comment]
Hi @claudioscordino,

The zoom buffer length (middle graph), on which the mean is computed is fixed to 5s length in capture mode. But if you click the 'Freeze display' button (capture continues in background but display is frozen), you can change its dimensions at will (either using the mouse wheel on the middle graph or moving the bars in the bottom graph). You can also click and move the graph in both windows to better adapt the zoom region of the middle graph.
Hope this helps,
Seb

**Comment by claudioscordino** [comment]
Thank you very much.
I think you should definitely put this information in the documentation somewhere. 
Best regards.
